### ISSUE TITLE
Incorrectly formatted BAM file

### ISSUE THREAD

**Issue by francois-lecoquierre** [abelson-lab/smMIP-tools#2]
Hi, 
Thank you so much for this new tool which will make things much easier !
However, I'm having trouble at having it to work, both on my data and on the smmip-tools example. 
The first script on the tutorial "map_smMIPs_extract_UMIs.R" seems to run fine, but the bam file is not recognized by samtools. 
I get this error when I try to open it : 

[E::sam_hrecs_error] Malformed key:value pair at line 2: "@SQ	SN:chr9	LN:1								"
samtools view: failed to add PG line to the header

I have tested on two systems, a personal computer and a bioinformatics server, and both result in the same error.
Here is the console extract, is there anything I'm doing wrong ?
[console.txt](https://github.com/abelson-lab/smMIP-tools/files/8803716/console.txt)
Thank you again, 
François

**Comment by BioSoft** [comment]
Hello François.
To be honest, I am not sure where the problem lies.
I executed the code from a fresh download and was able to use samtools successfully to view the content of control1_clean.bam.
I tried samtools/0.1.19, samtools/1.2 and samtools/1.9. All worked.
Are you still getting errors using either of these versions?
If you like, you can also send me your control1_clean.bam file. Lets make sure that it is not SmMIP-tools and that I can view it on my end.

**Comment by francois-lecoquierre** [comment]
Hi Sagi,
Thank you for your message. 
I used to test samtools 1.10 and 1.15
As you suggested I just tested on version 1.9 and now it works i can open the bam file like in the example.
However i cannot manage to display these bam on IGV, i get this error : 
Error encountered querying alignments: java.lang.ArrayIndexOutOfBoundsException: Index 4990 out of bounds for length 4682
I have tried two IGV versions, and to re-generate the index file with different samtools versions without success. Can it be due to the same origin ? 
François

**Comment by BioSoft** [comment]
Hi François. 
Typically you will want to look at specific genomic locations. For that, you can use the extract_reads.R code that we shared with SmMIP-tools.
Specifically, for the genomic location in the example, you can type:
Rscript extract_reads.R -f ../Example/bams/control1/control1_clean.bam -p chr9:5073712-5073857 -o ../Example/bams/control1/
If you want to upload all the reads to IGV, using "samtools view control1_clean.bam > control1_clean.sam" to load the sam should work.

Sagi
