### ISSUE TITLE
Error at ################ ASSIGN THE SMMIP NAME AND THE UMI SEQUENCE TO THE READS NAME

### ISSUE THREAD

**Issue by JohnChristin** [abelson-lab/smMIP-tools#3]
I'd like to use this tool to analyze some smMIP sequencing I've performed but when I get to this step I have the following error:

```
Error in h(simpleError(msg, call)) :
error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': 'data' must be of a vector type, was 'NULL'
5.
h(simpleError(msg, call))
4.
.handleSimpleError(function (cond)
.Internal(C_tryCatchHelper(addr, 1L, cond)), "'data' must be of a vector type, was 'NULL'",
base::quote(matrix(unlist(strsplit(suffix[-grep("flag", suffix)],
split = ":")), ncol = 2, byrow = TRUE)))
3.
matrix(unlist(strsplit(suffix[-grep("flag", suffix)], split = ":")),
ncol = 2, byrow = TRUE) at smMIPs_Functions.R#486
2.
as.data.frame(matrix(unlist(strsplit(suffix[-grep("flag", suffix)],
split = ":")), ncol = 2, byrow = TRUE)) at smMIPs_Functions.R#486
1.
adjust_readname(data)

```
I'm running R 4.3.2 

Thank you for making this tool.

**Comment by BioSoft** [comment]
Hi. Thank you for your email.
It appears there might be a discrepancy between the input and the format
required by the code.
Let's troubleshoot together. I'll need some additional information.
Firstly, could you confirm if you can successfully run smMIP-tools on the
demo data?
Additionally, please verify that your panel file is structured similarly to
the supplied Target_MIPgen.txt.

Sagi

**Comment by JohnChristin** [comment]
Thanks for the quick response. With the demo data I actually get a bit further but fail at a different step. The error message is below

```
Writing the clean bam file
[E::sam_hrecs_error] Malformed key:value pair at line 1: "@SQ	SN:chr9	LN:1								"
[E::sam_parse1] failed to parse header
[W::sam_read1_sam] Parse error at line 4
[E::sam_hrecs_error] Malformed key:value pair at line 1: "@SQ	SN:chr9	LN:1								"
[E::sam_hrecs_error] Malformed key:value pair at line 1: "@SQ	SN:chr9	LN:1								"
samtools sort: failed to change sort order header to 'SO:coordinate'

Error in value[[3L]](cond) : 'asBam' Error during sorting
  file: /var/folders/06/qhht1g3s2_d15yw9djf4641c0000gn/T//RtmpZ5js23/file2f8b7f2511a5
  SAM file: '/Users/johnchristin/smMIP/00_fastq/control1/control1_clean.sam'
Execution halted
```
And I've attached first two lines of my mipgen panel output

[smMIP_2lines.txt](https://github.com/abelson-lab/smMIP-tools/files/14089824/smMIP_2lines.txt)

**Comment by BioSoft** [comment]
Hi.
The second issue that you encountered was a result of a modification
introduced in the Rsamtools library in one of the recent versions. I have
addressed this by updating the map_smMIPs_extract_UMIs.R script.
Can you please download this updated script and let me know if you can run
smMIP-tools on the demo data (e.g, control1)?

Regarding the other error, the panel file appears to be in good order.
Nevertheless, it appears that smMIP-tool is encountering difficulties
linking mip_names to the reads, leading to an empty dataframe. I am eager
to assist you in resolving this issue. Would it be feasible for you to
share your smallest bam file?

My email is ***@***.*** It will be easier to communicate this.

This would greatly aid in our efforts to pinpoint and address the root
cause of the problem.


Thanks

**Comment by BioSoft** [comment]
Works
